{{- if .Values.mapproxy.enabled -}}
{{- $chartName := include "mapproxy.name" . -}}
{{- $releaseName := .Release.Name -}}
{{- $configmapName := include "configmap.fullname" . -}}
{{- $s3 := (include "common.s3.merged" .) | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
  labels:
    app: {{ $releaseName }}-{{ $chartName }}
    component: map-proxy-configmap
    environment: {{ .Values.environment }}
    release: {{ $releaseName }}
data:
  S3_ENDPOINT_URL: {{ $s3.endpointUrl | quote }}
  S3_BUCKET:  {{ $s3.tilesBucket | quote }}
  AWS_HTTPS: {{ $s3.sslEnabled | quote }}
  CORS_ENABLED: {{ .Values.mapproxy.env.cors.enabled | quote }}
  CORS_ALLOWED_HEADERS: {{ template "map-proxy.cors.allowedHeaders" . }}
  CORS_ALLOWED_ORIGIN: {{ .Values.mapproxy.env.cors.allowedOrigin | quote }}
  START_SCRIPT: {{ tpl (.Files.Get "config/start.sh") . | quote }}
  MAPPROXY_YAML: {{ tpl (.Files.Get "config/mapproxy.yaml") . | quote }}
  LOG_INI: {{ tpl (.Files.Get "config/log.ini") . | quote }}
{{- end }}
