{{- if .Values.mapproxy.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $chartName := include "mapproxy.name" . -}}
{{- $cloudProviderFlavor := include "mapproxy.cloudProviderFlavor" . -}}
{{- $serviceName := include "service.fullname" . -}}
{{- $nodePort := .Values.mapproxy.nodePort -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "mapproxy.environment" . }}
    release: {{ $releaseName }}
    {{- include "mapproxy.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.mapproxy.uwsgi.socket }}
      targetPort: {{ .Values.mapproxy.uwsgi.socket }}
      protocol: TCP
      name: http
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ $nodePort }}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    app.kubernetes.io/name: {{ include "mapproxy.name" . }}
    app.kubernetes.io/instance: {{ $releaseName }}
{{- end }}
