{{- if .Values.nginx.enabled -}}
{{- $fullName := include "mapproxy.fullname" . -}}
{{- $chartName := include "mapproxy.name" . -}}
{{- $cloudProviderDockerRegistryUrl := include "mapproxy.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "mapproxy.cloudProviderImagePullSecretName" . -}}
{{- $nginxConfigmapName := include "nginx-configmap.fullname" . }}
{{- $listOfSubPaths := include "listOfSubPaths" . | fromJsonArray -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-deployment" (include "nginx.fullname" .) }}
  labels:
    app: {{ $fullName | quote }}
    component: nginx-deployment
    environment: {{ include "mapproxy.environment" . }}
    release: {{ .Release.Name }}
    {{- include "mapproxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: {{ $fullName | quote }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ $fullName | quote }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-nginx
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      volumes:
        - name: nginx-base-config
          configMap:	
            name: {{ $nginxConfigmapName }}
          {{- if .Values.nginx.extraVolumes }}
            {{ tpl (toYaml .Values.nginx.extraVolumes) . | nindent 8 }}
          {{- end }}
      containers:
        - name: {{ $fullName | quote }}
          {{- with .Values.nginx.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ .tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            {{ if not (has "default.conf" $listOfSubPaths ) }}
            - name: nginx-base-config
              mountPath: "/etc/nginx/conf.d/default.conf"
              subPath: default.conf
            {{- end -}}
            {{ if not (has "nginx.conf" $listOfSubPaths )}}
            - name: nginx-base-config
              mountPath: "/etc/nginx/nginx.conf"
              subPath: nginx.conf
            {{- end -}}
            {{ if not (has "log_format.conf" $listOfSubPaths )}}
            - name: nginx-base-config
              mountPath: "/etc/nginx/log_format.conf"
              subPath: log_format.conf
            {{- end -}}
              {{- if .Values.nginx.extraVolumeMounts }}
                {{ toYaml .Values.nginx.extraVolumeMounts | nindent 12 }}
              {{- end }} 
          ports:
            - name: http
              containerPort: {{ .Values.nginx.targetPort }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /nginx_status
              port: {{ .Values.nginx.statusPort }}
          {{- if .Values.nginx.resources.enabled }}
          resources:
            {{- toYaml .Values.nginx.resources.value | nindent 12 }}
          {{- end }}
{{- end }}
